### ISSUE TITLE
Marco Teorico

### ISSUE THREAD

**Issue by UrielML** [UrielML/Proyecto_Final#6]
Realizar el Marco teórico el cual debe responder a las siguientes preguntas:
1. ¿Hay alguien trabajando en el problema?
2. ¿Como lo están haciendo?
3. ¿existen herramientas para este problema?
4. ¿Cuales? ¿Donde se encuentran?
5. ¿Libres de pago?
6. ¿Cuanto cuestan?

**Comment by jaivos45** [comment]
Encontré solo dos aplicaciones que mas se acercan a la funcionalidad del proyecto 
ya están documentadas
